// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Course struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	CourseCode   string
	LevelID      uuid.UUID
	DepartmentID uuid.UUID
}

type Department struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	FacultyID uuid.UUID
}

type Dev struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Password  string
}

type Faculty struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	UniversityID uuid.UUID
}

type Level struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Code      int32
}

type Material struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	CourseID  uuid.UUID
	CloudUrl  string
}

type University struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Alias     string
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	FirstName    string
	LastName     string
	OtherName    string
	Email        string
	MatricNumber string
	LevelID      uuid.UUID
	FacultyID    uuid.UUID
	DepartmentID uuid.UUID
	UniversityID uuid.UUID
	IsAdmin      bool
	Password     string
}
